name: Build and Zip Chrome Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Uncomment if needed
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Build extension
      #   run: npm run build

      # Create zip file directly from current directory
      - name: Create zip file
        run: |
          zip -r hs-nav.zip . \
          -x "*.git*" \
          -x "node_modules/**" \
          -x ".github/**" \
          -x "icons/search.png" \
          -x "README.md" \
          -x "LICENSE"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: hs-nav
          path: hs-nav.zip